test: &default
  adapter: postgresql
  encoding: unicode
  database: devtest_test
  user: dmitry

production:
  <<: *default
  database: devtest_development

staging:
  <<: *default
  database: devtest_development

development:
  <<: *default
  database: devtest_development
